### ISSUE TITLE
Move validation

### ISSUE THREAD

**Issue by irooori** [nicosrm/24-emb-chess#10]
It shall be validated if the passed move on the chess board is valid.

~~If the move is indeed valid, the LEDs shall be turned green for a short amount of time. Otherwise, don't move and turn the LEDs red.~~ --> moved to #25 

### Dependencies
- #20 
- #2

**Comment by nicosrm** [comment]
Validation logic for pawn was added in #21. Remaining is flashing the lights. I'd suggest to tackle this issue together with #4 when adding movement.
